var paragraphs = [],
    randomIndex;
pushParagraphs();

randomIndex = Math.floor(Math.random() * paragraphs.length);
var strArray = paragraphs[randomIndex].split(' ');

function pushParagraphs() {
    paragraphs.push("Mom is a great cook. She started cooking when she was three years old! I know that sounds silly, but she would help her mother cook. And, now I'm helping my mom cook. I like to make chicken the best. Baked chicken is my most favorite thing to make. It is also my favorite food to eat. One day, when mom was sick, I tried to make the chicken all by myself. I washed the chicken and put it in a pan in the oven to bake. When the bell rang to tell me the chicken was done, I opened the oven door. Guess what? The chicken was not cooked! I started to laugh. I laughed and laughed and laughed! Did you know what I did? I forgot to turn on the oven! Did you know what I did next? I called on the telephone for pizza to come to our house. Mom was happy that I 'cooked' by myself. She was happy that we could eat the pizza together. Guess what? We will have chicken some other night.");
    paragraphs.push("There is growing concern about the number of immigrants who are seeking asylum. Then there is the question of their safety. Many of them are so desperate to leave their own countries and start a new life in another that they will grasp at any opportunity which they believe will enable them to do this. Sadly, many of them risk life and limb and still do not fulfill their dream. Unscrupulous people are taking advantage of asylum seekers by promising to get them into the country of their choice by fair means or foul, provided they give them money. The desperate asylum seekers are parting with money which they have scrimped and saved for all their lives and are even taking the money which aging parents had set aside for a rainy day and giving it to these people. They have high hopes of a safer, better life and the money seems well worth it.");
    paragraphs.push("Manufacturers are currently competing with each other to produce a form of green packaging. Packaging is an important part of marketing these days, but much of it is a threat to the environment. There are two reasons for this. The production of such packaging uses up a great deal of energy and the cartons, wrappers, etc are often difficult to dispose of when they become waste material. People in most countries have become aware of the damage which modern living is doing to the environment, and many of them are concerning themselves with the conservation of the environment for future generations. Thus, both politicians and scientists are now looking at the issues of energy-saving and waste disposal with a view to making them more environmentally-friendly.");
    paragraphs.push("Some scientists say time is governed by the movement of matter in our universe. They say time flows forward because the universe is expanding. Some say it will stop expanding some day and will begin to move in the opposite direction, to grow smaller. Some believe time will also begin to flow in the opposite direction from the future to the past. Can time move backward? Most people have no trouble agreeing that time moves forward. We see people born and then grow old. We remember the past, but we do not know the future. We know a film is moving forward if it shows a glass falling off a table and breaking into many pieces. If the film were moving backward, the pieces would re-join to form a glass and jump back up onto the table. No one has ever seen this happen. Except in a film. ");
    paragraphs.push("Did you know that there's a World Chocolate Day? It takes place each year on 7 July. To celebrate it, read about the history of chocolate and the interesting journey from cocoa bean to chocolate bar. A brief history of chocolate: Chocolate was first used as a drink over 3,500 years ago in Central America. It was very popular with the Mayans and the Aztecs, who mixed cocoa beans with vanilla or chilli peppers. In fact, cocoa beans were so important to them that they were used as money. Cocoa was first grown in Ecuador, which was, for a long time, the world's number-one producer of cocoa beans. It is still one of the top ten producers of the beans, but nowadays more than 70 per cent of cocoa beans come from West Africa.");
    paragraphs.push("In a recent survey, it was found that 25 percent of the women interviewed reported drying and burning of the skin after using certain soaps, ten percent had eye and nasal irritations after using certain perfumes, and eight percent had cracked lips after using certain lipsticks. The most common symptoms of allergic dermatitis are extremely dry skin, redness with swelling and itching. The products most likely to cause this condition are lipstick, nail polish, soap, hair preparations, deodorants, and perfumes. Various drugs are being developed for the relief of allergy sufferers. However, your best help is to convert to a cosmetic product to which you have no harmful reaction. Remember that the product is not at fault or in any way injurious; it is your particular sensitivity to it that creates the problem. A line of hypoallergenic cosmetics that are relatively free from substances that have been found to create allergic reactions is on the market.");
}